spring: 
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api_estagios_pi_ifsc?useTimezone=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: none
    show-sql: false

# Flyway Configs

#flyway: 
#  url: jdbc:mysql://localhost:3306/
#  schemas: estagios
#  user: root
#  password: root

# Jackson Configs
# spring.jackson.default-property-inclusion=non_null
